class_name ClueData
extends Resource


enum DiaryPages {
	CONTRADA_ABBANDONATA,
	CASCATA,
	VALLE_OSCURA,
	PONTE,
	ABBAZIA,
	CAPANNO_DEI_CACCIATORI,
	RADURA_ALIENA,
	DIARIO_ABBANDONATO
}

enum ClueID {
	FORI_PROIETTILI,
	LIQUIDO_GIALLO,
	FOTO_FAMIGLIA,
	DIPINTO_CASCATA,
	OCCHIALI_LUIGINO,
	SCARPA_DONNA,
	SOLCHI_DITA_TERRENO,
	FOGLIO_PARTITE_NASCONDINO,
	SANGUE_VALLE,
	DIARIO_AGNESE,
	DISEGNO_BAMBINI_PONTE,
	PORTA_SFONDATA,
	FUCILE_ROTTO,
	FOGLIA_ALIENA,
	DISEGNO_PONTE_CHIESA,
	DISEGNI_TUNNEL,
	COLLANA_CROCIFISSO,
	MATITE
}


@export var diary_page_ID: DiaryPages
@export var clue_ID: ClueID
